import { StubScreen } from '@/components/StubScreen';
import { BattleScreen } from '@/screens/Battle/BattleScreen';
import { ChartScreen } from '@/screens/Chart/ChartScreen';
import { CodexScreen } from '@/screens/Codex/CodexScreen';
import { CollectionScreen } from '@/screens/Collection/CollectionScreen';
import { EndingScreen } from '@/screens/Ending/EndingScreen';
import { EventScreen } from '@/screens/Event/EventScreen';
import { FinaleScreen } from '@/screens/Finale/FinaleScreen';
import { HangarScreen } from '@/screens/Hangar/HangarScreen';
import { InterstitialScreen } from '@/screens/Interstitial/InterstitialScreen';
import { MapScreen } from '@/screens/Map/MapScreen';
import { MenuScreen } from '@/screens/Menu/MenuScreen';
import { PrologueScreen } from '@/screens/Prologue/PrologueScreen';
import { PuzzleScreen } from '@/screens/Puzzle/PuzzleScreen';
import { RewardsScreen } from '@/screens/Rewards/RewardsScreen';
import { RunSetupScreen } from '@/screens/RunSetup/RunSetupScreen';
import { SettingsScreen } from '@/screens/Settings/SettingsScreen';
import { ShipyardScreen } from '@/screens/Shipyard/ShipyardScreen';
import { ShopScreen } from '@/screens/Shop/ShopScreen';
import { SummaryScreen } from '@/screens/Summary/SummaryScreen';
import { useAppStore } from '@/stores/appStore';

export const Router = () => {
  const screen = useAppStore((s) => s.screen);
  if (screen === 'menu') return <MenuScreen />;
  if (screen === 'settings') return <SettingsScreen />;
  if (screen === 'battle') return <BattleScreen />;
  if (screen === 'map') return <MapScreen />;
  if (screen === 'event') return <EventScreen />;
  if (screen === 'puzzle') return <PuzzleScreen />;
  if (screen === 'shop') return <ShopScreen />;
  if (screen === 'shipyard') return <ShipyardScreen />;
  if (screen === 'rewards') return <RewardsScreen />;
  if (screen === 'summary') return <SummaryScreen />;
  if (screen === 'codex') return <CodexScreen />;
  if (screen === 'chart') return <ChartScreen />;
  if (screen === 'hangar') return <HangarScreen />;
  if (screen === 'collection') return <CollectionScreen />;
  if (screen === 'runSetup') return <RunSetupScreen />;
  if (screen === 'prologue') return <PrologueScreen />;
  if (screen === 'interstitial') return <InterstitialScreen />;
  if (screen === 'finale') return <FinaleScreen />;
  if (screen === 'ending') return <EndingScreen />;
  return <StubScreen screen={screen} />;
};
